### PR TITLE
Update client logos to new alignment template

### PR DESCRIPTION
**Pull request by kwm14**
## Done

- Updated client logos to use our new alignment template, so they sit on an imaginary baseline which will give logos:

  - A comparable visual weight
  - Fit in a given height / width
  - Reduces elongated or very thin logos to appear a lot smaller

## QA
- `./run`
- Visit homepage
- See that the updated client logos have comparable visual weight

## Issue / Card
- Fixes - https://github.com/canonical-websites/vanillaframework.io/issues/170

### CODE REVIEW

**Comment by kwm14** [comment]
@anthonydillon they should be smaller but not that small 😞 

The logos should be 145 x 145px as seen on snapcraft.io

screen shot 2018-09-12 at 11 14 18

But for some reason on vf.io the logos are pulling in at 88px with a 30px margin all round. I thought replacing the links would update but seems to not have...

**Comment by Caleb-Ellis** [comment]
@kwm14 Looks like the new images have a lot of empty space above and below. Since the inline images have a max-height, it's truncating the width to keep aspect ratio consistent.

**Comment by spencerbygraves** [comment]
@kwm14 @Caleb-Ellis @anthonydillon Yes, they do look too small...

**Comment by kwm14** [comment]
> @kwm14 Looks like the new images have a lot of empty space above and below. Since the inline images have a max-height, it's truncating the width to keep aspect ratio consistent.

@Caleb-Ellis How do I get around that as the logos seem to be working fine on https://snapcraft.io/ 😕

**Comment by Caleb-Ellis** [comment]
@kwm14 They're using a currently non-Vanilla pattern (p-fluid-grid) that doesn't add any margin to the image containers. In my opinion the images shouldn't have unnecessary empty space, and margins should be set with CSS, otherwise you can only use those images in places where you want a square container. For example if I use one of those images in navigation:

screenshot_11

**Comment by kwm14** [comment]
@deadlight I've updated the markup 👍 over to you to add fancy utilities for mobile and tablet 😃

**Comment by deadlight** [comment]
@kwm14 I think that's fixed it (It's something that we should consider for Vanilla but it'll need to be a bit more robust)

**Comment by kwm14** [comment]
@anthonydillon logos now fixed and ready for another review 😄 agreed this will be a temporary fix for inline images now and when we start v2.0 we will update to use fluid layout 💯

**Pull request merged**
