### PR TITLE
Update the Vanilla dependency to v.1.6.3

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Update the Vanilla dependency to v.1.6.3 with a hotfix for a max-width bug.

## QA
- Pull code
- Run `./run`
- Go to http://0.0.0.0:8014/
- Click around and check everything is looking good

## Issue / Card
https://github.com/vanilla-framework/vanilla-framework/issues/1471

### CODE REVIEW

**Comment by kwm14** [comment]
## Design review

Looking good @anthonydillon just one quick change :slightly_smiling_face:

- [ ] Update navigation from `grey` to our new default `white` version as seen on docs [here](https://docs.vanillaframework.io/en/patterns/navigation)

**Comment by anthonydillon** [comment]
@kwm14 fixed, thanks.

**Comment by spencerbygraves** [comment]
@anthonydillon can the docs header be updated as part of this? There's a jump in size when you go to docs:

image

**Comment by anthonydillon** [comment]
Yes, I'll try and update the docs p project with the latest Vanilla but it is in a different codebase so will be another PR.

**Pull request merged**
