### PR TITLE
Update style of browser-support page

### LINKED ISSUE #139: Update /browser-support page styling and layout
## Summary

Update /browser-support page styling and layout.

## Process
- /browser-support Google doc [here](https://docs.google.com/document/d/1flcSinNnjOJw88ooVQfUjQW8ZDHSXOe2cTHmgwIEx6I/edit#heading=h.1qetfww1cwmc)
- Original design issue [here](https://github.com/ubuntudesign/vanilla-design/issues/282)
- Intro paragraph: `h4`
- Browser and OS icons:
   - Chrome: https://assets.ubuntu.com/v1/09a6a50e-vf.io-chrome.png
   - Firefox: https://assets.ubuntu.com/v1/a45d30aa-vf.io-firefox.svg
   - Safari: https://assets.ubuntu.com/v1/a030d872-vf.io-safari.svg
   - IE: https://assets.ubuntu.com/v1/165a2220-vf.io-ie.svg
   - Edge: https://assets.ubuntu.com/v1/de0673bb-vf.io-edge.svg
   - Opera: https://assets.ubuntu.com/v1/74738acc-vf.io-opera.svg

## Screenshot
browser-support-004

### PR DESCRIPTION
**Pull request by deadlight**
## Done

Updated the browser support page

## QA

 - `./run`
 - Go to /browser-support
 - Check against the [copydoc](https://docs.google.com/document/d/1flcSinNnjOJw88ooVQfUjQW8ZDHSXOe2cTHmgwIEx6I/edit#)
 - Check against the [design](https://app.zenhub.com/workspace/o/canonical-websites/vanillaframework.io/issues/139)

## Issue / Card

Fixes #139

### CODE REVIEW

**Comment by deadlight** [comment]
Oh yeah, I forgot that coding stadards and tests were a thing.... passing now

**Comment by kwm14** [comment]
## Design review
- @deadlight updates look really good 💯 
- just one small copy amend
- [ ] remove 'Last update: 01 August 2018' from bottom of the page

**Comment by deadlight** [comment]
@kwm14 I can't get the demo to rebuild but I fixed those things.

**Comment by kwm14** [comment]
Yaaaas @deadlight managed to rebuild demo. LGTM 👍

**Pull request merged**
