### PR TITLE
Design review tweaks

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Completed the list of design updates.

## QA
- Pull down the code and run `npm run develop`
- Check each todo in the [related issue](https://github.com/canonical-websites/vanillaframework.io/issues/11)

## Details
Fixes https://github.com/canonical-websites/vanillaframework.io/issues/11

### CODE REVIEW

**Comment by anthonydillon** [comment]
@yaili just waiting on a design review here.

**Comment by yaili** [comment]
Some notes:
- [ ] Will the margin below the nav disappear with the next Vanilla release?
- [ ] The nav should be the light version? See https://github.com/ubuntudesign/vanilla-design/tree/master/Navigation
- [ ] Border between sections are missing
- [ ] Could we have the syntax highlighting like in docs?
- [ ] The strips should be "deep" 
- [ ] Remove paragraph text from Get involved section
- Icons for Get involved:
  - [ ] Slack: https://assets.ubuntu.com/v1/5853f458-icon-slack.svg
  - [ ] Twitter: https://assets.ubuntu.com/v1/7546afeb-icon-twitter.svg
  - [ ] GitHub: https://assets.ubuntu.com/v1/61d83c7e-icon-github.svg

**Comment by anthonydillon** [comment]
@yaili all done and ready for another review.

@deadlight after so many updates I would like to have this one code reviewed again please.

**Comment by deadlight** [comment]
@anthonydillon code looks good. Still needs a design +1 before merge.

**Comment by anthonydillon** [comment]
Thanks, @deadlight. Yeah, only one last hurdle to go.

**Comment by yaili** [comment]
@anthonydillon 
I'm having problems running the branch. Did `npm run develop`, got error, said to do `bundle install` and now getting another error: `public_suffix-2.0.5 requires ruby version >= 2.0, which is incompatible with the current version, ruby 1.9.3p551`

**Comment by anthonydillon** [comment]
@yaili looks like we really need to update your version of Ruby. Lets catch up on IRC.

**Comment by anthonydillon** [comment]
@yaili updated the latest version of the theme. Running `./run` should work now. Let me know if you have any trouble.

**Comment by anthonydillon** [comment]
Demo: http://vanillaframework.io-fix-design-review-points.demo.haus/

**Comment by yaili** [comment]
@barrymcgee the demo isn't working… "502 Bad Gateway"

**Comment by barrymcgee** [comment]
@yaili Tried rebuilding but still getting "502 - Bad gateway", @nottrobin - can you take a look pls?

**Comment by yaili** [comment]
Adding -1 label as I can't verify if the changes have been made yet: https://github.com/canonical-websites/vanillaframework.io/issues/11

**Comment by anthonydillon** [comment]
@yaili @joanasa89 Would you mind reviewing this branch please.

Demo: http://vanillaframework.io-fix-design-review-points.demo.haus/

**Comment by yaili** [comment]
- [ ] Remove the double border above the footer
- [ ] The padding in inputs was wrong in Vanilla, @pmahnke fixed it - is this using the latest Vanilla, or is that update not available yet? I think this will help with the different heights with input/button in newsletter box
- [ ] Navigation is breaking when viewport is reduced…
screen shot 2017-06-07 at 14 54 47

- [ ] … and at S screens (doesn't look like Vanilla)
screen shot 2017-06-07 at 14 54 40

**Comment by anthonydillon** [comment]
>The padding in inputs was wrong in Vanilla, @pmahnke fixed it - is this using the latest Vanilla, or is that update not available yet? I think this will help with the different heights with input/button in newsletter box

It's on the latest Vanilla but Peters change might not have been released yet.

**Comment by yaili** [comment]
Is it the same demo link, I don't see any changes: http://vanillaframework.io-fix-design-review-points.demo.haus/

Just another note, the navigation seems to be using a large font size than specified: https://github.com/ubuntudesign/vanilla-design/blob/master/Navigation/navigation.md

**Comment by anthonydillon** [comment]
Sorry, demo has been updated: http://vanillaframework.io-fix-design-review-points.demo.haus/

**Comment by spencerbygraves** [comment]
There is a small issue with button styling in the subscribe section but these will be fixed upstream.
image

**Comment by kwm14** [comment]
Also in 'WHO’S USING VANILLA' section we are using old logo versions for MAAS, Juju and Landscape.

screen shot 2017-06-23 at 10 38 54

**Pull request merged**
