### PR TITLE
Import vanilla-framework directly, replacing VBT

### LINKED ISSUE #70: Inconsistent underlining on hover of header button vs. header button text
1\. Go to any page on vanillaframework.io.
2\. Mouse over the empty part of any of the header buttons.
3\. Mouse over the text in the header button.

What happens:
2\. The text has a thin underline.
3\. The text has a thick underline.

vanilla-header-underlining-1

What should happen: either
2\. The text has a thin underline.
3\. The text has a thin underline.

Or
2\. The text has no underline.
3\. The text has no underline.

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

- Import `vanilla-framework` directly instead of using `vanilla-brochure-theme`
- Remove temp fixes which have now moved upstream to Vanilla
- Pulling Vanilla directly has squashed the nav hover bug as outlined in #70 

## QA

- Pull code
- Run `./run serve --watch`
- Verify nothing has broken (oh, where art thou Percy!)
- Check there is now no underline when hovering over primary nav items

## Issue / Card

Fixes #70

### CODE REVIEW

**Comment by kwm14** [comment]
## Nav design review

- button hover looks good +1
- [ ] bug when navigation from Browser support > Coding standards > Contribute. The navigation bar moves either 10px to the right or left depending on which header tab you click

**Comment by barrymcgee** [comment]
@kwm14 Nav jump issue is upstream in Vanilla, have created an issue here: https://github.com/vanilla-framework/vanilla-framework/issues/1275

@pmahnke Have addressed your issues, ready for re-review.

**Comment by kwm14** [comment]
@barrymcgee ok great thanks. Can I design review from existing demo link?

**Comment by barrymcgee** [comment]
New demo link: http://vanillaframework.io-pr-79.run.demo.haus

**Comment by barrymcgee** [comment]
@pmahnke I've raised an issue upstream for this https://github.com/vanilla-framework/vanilla-framework/issues/1276

**Comment by barrymcgee** [comment]
@kwm14 http://vanillaframework.io-pr-80.run.demo.haus/

**Pull request merged**
